<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Chapter 37 Practical. Using R | Statistical Techniques for Biological and Environmental Sciences</title>
  <meta name="description" content="This is a lab book for the University of Stirling second year undergraduate Biological and Environmental Sciences statistics module." />
  <meta name="generator" content="bookdown 0.27 and GitBook 2.6.7" />

  <meta property="og:title" content="Chapter 37 Practical. Using R | Statistical Techniques for Biological and Environmental Sciences" />
  <meta property="og:type" content="book" />
  
  <meta property="og:description" content="This is a lab book for the University of Stirling second year undergraduate Biological and Environmental Sciences statistics module." />
  <meta name="github-repo" content="bradduthie/statistical_techniques" />

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Chapter 37 Practical. Using R | Statistical Techniques for Biological and Environmental Sciences" />
  
  <meta name="twitter:description" content="This is a lab book for the University of Stirling second year undergraduate Biological and Environmental Sciences statistics module." />
  

<meta name="author" content="Brad Duthie" />


<meta name="date" content="2023-04-09" />

  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="reporting-statistics.html"/>
<link rel="next" href="Week13.html"/>
<script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/fuse.js@6.4.6/dist/fuse.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />








<link href="libs/anchor-sections-1.1.0/anchor-sections.css" rel="stylesheet" />
<link href="libs/anchor-sections-1.1.0/anchor-sections-hash.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.1.0/anchor-sections.js"></script>


<style type="text/css">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { font-weight: bold; } /* Alert */
code span.an { font-style: italic; } /* Annotation */
code span.cf { font-weight: bold; } /* ControlFlow */
code span.co { font-style: italic; } /* Comment */
code span.cv { font-style: italic; } /* CommentVar */
code span.do { font-style: italic; } /* Documentation */
code span.dt { text-decoration: underline; } /* DataType */
code span.er { font-weight: bold; } /* Error */
code span.in { font-style: italic; } /* Information */
code span.kw { font-weight: bold; } /* Keyword */
code span.pp { font-weight: bold; } /* Preprocessor */
code span.wa { font-style: italic; } /* Warning */
</style>

<style type="text/css">
/* Used with Pandoc 2.11+ new --citeproc when CSL is used */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
}
.hanging div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">Statistical Techniques</a></li>

<li class="divider"></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>Preface</a>
<ul>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#why-this-module-is-important"><i class="fa fa-check"></i>Why this module is important</a></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#ILOs"><i class="fa fa-check"></i>Intended learning outcomes (ILOs)</a></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#accessibility"><i class="fa fa-check"></i>Accessibility</a></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#teaching_overview"><i class="fa fa-check"></i>Teaching overview</a>
<ul>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#book_chapters"><i class="fa fa-check"></i>Book chapters</a></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#additional_readings"><i class="fa fa-check"></i>Additional readings</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#Canvas"><i class="fa fa-check"></i>Canvas</a></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#assessment-overview"><i class="fa fa-check"></i>Assessment overview</a>
<ul>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#tests"><i class="fa fa-check"></i>Tests</a></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#exams"><i class="fa fa-check"></i>Exams</a></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#feedback"><i class="fa fa-check"></i>Feedback</a></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#extenuating_circumstances"><i class="fa fa-check"></i>Extenuating circumstances</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#practicals"><i class="fa fa-check"></i>Practicals</a></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#help"><i class="fa fa-check"></i>Optional help hours</a></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#jamovi"><i class="fa fa-check"></i>Jamovi statistical software</a></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#timetable"><i class="fa fa-check"></i>Timetable</a></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#license"><i class="fa fa-check"></i>License</a></li>
</ul></li>
<li class="part"><span><b>I Background mathematics and data organisation</b></span></li>
<li class="chapter" data-level="" data-path="Week1.html"><a href="Week1.html"><i class="fa fa-check"></i>Week 1 Overview</a></li>
<li class="chapter" data-level="1" data-path="Chapter_1.html"><a href="Chapter_1.html"><i class="fa fa-check"></i><b>1</b> Background mathematics</a>
<ul>
<li class="chapter" data-level="1.1" data-path="Chapter_1.html"><a href="Chapter_1.html#numbers-and-operations"><i class="fa fa-check"></i><b>1.1</b> Numbers and operations</a></li>
<li class="chapter" data-level="1.2" data-path="Chapter_1.html"><a href="Chapter_1.html#logarithms"><i class="fa fa-check"></i><b>1.2</b> Logarithms</a></li>
<li class="chapter" data-level="1.3" data-path="Chapter_1.html"><a href="Chapter_1.html#order-of-operations"><i class="fa fa-check"></i><b>1.3</b> Order of operations</a></li>
</ul></li>
<li class="chapter" data-level="2" data-path="Chapter_2.html"><a href="Chapter_2.html"><i class="fa fa-check"></i><b>2</b> Data organisation</a>
<ul>
<li class="chapter" data-level="2.1" data-path="Chapter_2.html"><a href="Chapter_2.html#tidy-data"><i class="fa fa-check"></i><b>2.1</b> Tidy data</a></li>
<li class="chapter" data-level="2.2" data-path="Chapter_2.html"><a href="Chapter_2.html#data-files"><i class="fa fa-check"></i><b>2.2</b> Data files</a></li>
<li class="chapter" data-level="2.3" data-path="Chapter_2.html"><a href="Chapter_2.html#managing-data-files"><i class="fa fa-check"></i><b>2.3</b> Managing data files</a></li>
</ul></li>
<li class="chapter" data-level="3" data-path="Chapter_3.html"><a href="Chapter_3.html"><i class="fa fa-check"></i><b>3</b> Practical: Preparing data</a>
<ul>
<li class="chapter" data-level="3.1" data-path="Chapter_3.html"><a href="Chapter_3.html#exercise-1-transferring-data-to-a-spreadsheet"><i class="fa fa-check"></i><b>3.1</b> Exercise 1: Transferring data to a spreadsheet</a></li>
<li class="chapter" data-level="3.2" data-path="Chapter_3.html"><a href="Chapter_3.html#exercise-2-making-spreadsheet-data-tidy"><i class="fa fa-check"></i><b>3.2</b> Exercise 2: Making spreadsheet data tidy</a></li>
<li class="chapter" data-level="3.3" data-path="Chapter_3.html"><a href="Chapter_3.html#exercise-3-making-data-tidy-again"><i class="fa fa-check"></i><b>3.3</b> Exercise 3: Making data tidy again</a></li>
<li class="chapter" data-level="3.4" data-path="Chapter_3.html"><a href="Chapter_3.html#exercise-4-tidy-data-and-spreadsheet-calculations"><i class="fa fa-check"></i><b>3.4</b> Exercise 4: Tidy data and spreadsheet calculations</a></li>
<li class="chapter" data-level="3.5" data-path="Chapter_3.html"><a href="Chapter_3.html#summary"><i class="fa fa-check"></i><b>3.5</b> Summary</a></li>
</ul></li>
<li class="part"><span><b>II Statistical concepts</b></span></li>
<li class="chapter" data-level="" data-path="Week2.html"><a href="Week2.html"><i class="fa fa-check"></i>Week 2 Overview</a></li>
<li class="chapter" data-level="4" data-path="Chapter_4.html"><a href="Chapter_4.html"><i class="fa fa-check"></i><b>4</b> Populations and samples</a></li>
<li class="chapter" data-level="5" data-path="Chapter_5.html"><a href="Chapter_5.html"><i class="fa fa-check"></i><b>5</b> Types of variables</a></li>
<li class="chapter" data-level="6" data-path="Chapter_6.html"><a href="Chapter_6.html"><i class="fa fa-check"></i><b>6</b> Accuracy, precision, and units</a>
<ul>
<li class="chapter" data-level="6.1" data-path="Chapter_6.html"><a href="Chapter_6.html#accuracy"><i class="fa fa-check"></i><b>6.1</b> Accuracy</a></li>
<li class="chapter" data-level="6.2" data-path="Chapter_6.html"><a href="Chapter_6.html#precision"><i class="fa fa-check"></i><b>6.2</b> Precision</a></li>
<li class="chapter" data-level="6.3" data-path="Chapter_6.html"><a href="Chapter_6.html#systems-of-units"><i class="fa fa-check"></i><b>6.3</b> Systems of units</a></li>
<li class="chapter" data-level="6.4" data-path="Chapter_6.html"><a href="Chapter_6.html#other-examples-of-units"><i class="fa fa-check"></i><b>6.4</b> Other examples of units</a>
<ul>
<li class="chapter" data-level="6.4.1" data-path="Chapter_6.html"><a href="Chapter_6.html#units-of-density"><i class="fa fa-check"></i><b>6.4.1</b> Units of density</a></li>
<li class="chapter" data-level="6.4.2" data-path="Chapter_6.html"><a href="Chapter_6.html#mass-of-metal-discharged-from-a-catchment"><i class="fa fa-check"></i><b>6.4.2</b> Mass of metal discharged from a catchment</a></li>
<li class="chapter" data-level="6.4.3" data-path="Chapter_6.html"><a href="Chapter_6.html#soil-carbon-inventories"><i class="fa fa-check"></i><b>6.4.3</b> Soil carbon inventories</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="7" data-path="Chapter_7.html"><a href="Chapter_7.html"><i class="fa fa-check"></i><b>7</b> Uncertainty propagation</a>
<ul>
<li class="chapter" data-level="7.1" data-path="Chapter_7.html"><a href="Chapter_7.html#adding-or-subtracting-errors"><i class="fa fa-check"></i><b>7.1</b> Adding or subtracting errors</a></li>
<li class="chapter" data-level="7.2" data-path="Chapter_7.html"><a href="Chapter_7.html#multiplying-or-dividing-errors"><i class="fa fa-check"></i><b>7.2</b> Multiplying or dividing errors</a></li>
<li class="chapter" data-level="7.3" data-path="Chapter_7.html"><a href="Chapter_7.html#applying-formulas-for-combining-errors"><i class="fa fa-check"></i><b>7.3</b> Applying formulas for combining errors</a></li>
</ul></li>
<li class="chapter" data-level="8" data-path="Chapter_8.html"><a href="Chapter_8.html"><i class="fa fa-check"></i><b>8</b> Practical. Introduction to Jamovi</a>
<ul>
<li class="chapter" data-level="8.1" data-path="Chapter_8.html"><a href="Chapter_8.html#summary_statistics_02"><i class="fa fa-check"></i><b>8.1</b> Exercise for summary statistics</a></li>
<li class="chapter" data-level="8.2" data-path="Chapter_8.html"><a href="Chapter_8.html#transforming_variables_02"><i class="fa fa-check"></i><b>8.2</b> Exercise on transforming variables</a></li>
<li class="chapter" data-level="8.3" data-path="Chapter_8.html"><a href="Chapter_8.html#computing_variables_02"><i class="fa fa-check"></i><b>8.3</b> Exercise on computing variables</a></li>
<li class="chapter" data-level="8.4" data-path="Chapter_8.html"><a href="Chapter_8.html#summary-1"><i class="fa fa-check"></i><b>8.4</b> Summary</a></li>
</ul></li>
<li class="part"><span><b>III Summary statistics</b></span></li>
<li class="chapter" data-level="" data-path="Week3.html"><a href="Week3.html"><i class="fa fa-check"></i>Week 3 Overview</a></li>
<li class="chapter" data-level="9" data-path="Chapter_9.html"><a href="Chapter_9.html"><i class="fa fa-check"></i><b>9</b> Decimal places, significant figures, and rounding</a>
<ul>
<li class="chapter" data-level="9.1" data-path="Chapter_9.html"><a href="Chapter_9.html#decimal-places-and-significant-figures"><i class="fa fa-check"></i><b>9.1</b> Decimal places and significant figures</a></li>
<li class="chapter" data-level="9.2" data-path="Chapter_9.html"><a href="Chapter_9.html#rounding"><i class="fa fa-check"></i><b>9.2</b> Rounding</a></li>
</ul></li>
<li class="chapter" data-level="10" data-path="Chapter_10.html"><a href="Chapter_10.html"><i class="fa fa-check"></i><b>10</b> Graphs</a>
<ul>
<li class="chapter" data-level="10.1" data-path="Chapter_10.html"><a href="Chapter_10.html#histograms"><i class="fa fa-check"></i><b>10.1</b> Histograms</a></li>
<li class="chapter" data-level="10.2" data-path="Chapter_10.html"><a href="Chapter_10.html#barplots-and-pie-charts"><i class="fa fa-check"></i><b>10.2</b> Barplots and pie charts</a></li>
<li class="chapter" data-level="10.3" data-path="Chapter_10.html"><a href="Chapter_10.html#box-whisker-plots"><i class="fa fa-check"></i><b>10.3</b> Box-whisker plots</a></li>
</ul></li>
<li class="chapter" data-level="11" data-path="Chapter_11.html"><a href="Chapter_11.html"><i class="fa fa-check"></i><b>11</b> Measures of central tendency</a>
<ul>
<li class="chapter" data-level="11.1" data-path="Chapter_11.html"><a href="Chapter_11.html#the-mean"><i class="fa fa-check"></i><b>11.1</b> The mean</a></li>
<li class="chapter" data-level="11.2" data-path="Chapter_11.html"><a href="Chapter_11.html#the-mode"><i class="fa fa-check"></i><b>11.2</b> The mode</a></li>
<li class="chapter" data-level="11.3" data-path="Chapter_11.html"><a href="Chapter_11.html#the-median-and-quantiles"><i class="fa fa-check"></i><b>11.3</b> The median and quantiles</a></li>
</ul></li>
<li class="chapter" data-level="12" data-path="Chapter_12.html"><a href="Chapter_12.html"><i class="fa fa-check"></i><b>12</b> Measures of spread</a>
<ul>
<li class="chapter" data-level="12.1" data-path="Chapter_12.html"><a href="Chapter_12.html#the-range"><i class="fa fa-check"></i><b>12.1</b> The range</a></li>
<li class="chapter" data-level="12.2" data-path="Chapter_12.html"><a href="Chapter_12.html#the-inter-quartile-range"><i class="fa fa-check"></i><b>12.2</b> The inter-quartile range</a></li>
<li class="chapter" data-level="12.3" data-path="Chapter_12.html"><a href="Chapter_12.html#the-variance"><i class="fa fa-check"></i><b>12.3</b> The variance</a></li>
<li class="chapter" data-level="12.4" data-path="Chapter_12.html"><a href="Chapter_12.html#the-standard-deviation"><i class="fa fa-check"></i><b>12.4</b> The standard deviation</a></li>
<li class="chapter" data-level="12.5" data-path="Chapter_12.html"><a href="Chapter_12.html#the-coefficient-of-variation"><i class="fa fa-check"></i><b>12.5</b> The coefficient of variation</a></li>
<li class="chapter" data-level="12.6" data-path="Chapter_12.html"><a href="Chapter_12.html#the-standard-error"><i class="fa fa-check"></i><b>12.6</b> The standard error</a></li>
</ul></li>
<li class="chapter" data-level="13" data-path="Chapter_13.html"><a href="Chapter_13.html"><i class="fa fa-check"></i><b>13</b> <em>Practical</em>. Plotting and statistical summaries in Jamovi</a>
<ul>
<li class="chapter" data-level="13.1" data-path="Chapter_13.html"><a href="Chapter_13.html#reorganise-the-dataset-into-a-tidy-format"><i class="fa fa-check"></i><b>13.1</b> Reorganise the dataset into a tidy format</a></li>
<li class="chapter" data-level="13.2" data-path="Chapter_13.html"><a href="Chapter_13.html#histograms-and-box-whisker-plots"><i class="fa fa-check"></i><b>13.2</b> Histograms and box-whisker plots</a></li>
<li class="chapter" data-level="13.3" data-path="Chapter_13.html"><a href="Chapter_13.html#calculate-summary-statistics"><i class="fa fa-check"></i><b>13.3</b> Calculate summary statistics</a></li>
<li class="chapter" data-level="13.4" data-path="Chapter_13.html"><a href="Chapter_13.html#reporting-decimals-and-significant-figures"><i class="fa fa-check"></i><b>13.4</b> Reporting decimals and significant figures</a></li>
<li class="chapter" data-level="13.5" data-path="Chapter_13.html"><a href="Chapter_13.html#comparing-across-sites"><i class="fa fa-check"></i><b>13.5</b> Comparing across sites</a></li>
</ul></li>
<li class="part"><span><b>IV Probability models and the Central Limit Theorem</b></span></li>
<li class="chapter" data-level="" data-path="Week4.html"><a href="Week4.html"><i class="fa fa-check"></i>Week 4 Overview</a></li>
<li class="chapter" data-level="14" data-path="Chapter_14.html"><a href="Chapter_14.html"><i class="fa fa-check"></i><b>14</b> Introduction to probability models</a>
<ul>
<li class="chapter" data-level="14.1" data-path="Chapter_14.html"><a href="Chapter_14.html#an-instructive-example"><i class="fa fa-check"></i><b>14.1</b> An instructive example</a></li>
<li class="chapter" data-level="14.2" data-path="Chapter_14.html"><a href="Chapter_14.html#biological-applications"><i class="fa fa-check"></i><b>14.2</b> Biological applications</a></li>
<li class="chapter" data-level="14.3" data-path="Chapter_14.html"><a href="Chapter_14.html#sampling-with-and-without-replacement"><i class="fa fa-check"></i><b>14.3</b> Sampling with and without replacement</a></li>
<li class="chapter" data-level="14.4" data-path="Chapter_14.html"><a href="Chapter_14.html#probability-distributions"><i class="fa fa-check"></i><b>14.4</b> Probability distributions</a>
<ul>
<li class="chapter" data-level="14.4.1" data-path="Chapter_14.html"><a href="Chapter_14.html#binomial-distribution"><i class="fa fa-check"></i><b>14.4.1</b> Binomial distribution</a></li>
<li class="chapter" data-level="14.4.2" data-path="Chapter_14.html"><a href="Chapter_14.html#poisson-distribution"><i class="fa fa-check"></i><b>14.4.2</b> Poisson distribution</a></li>
<li class="chapter" data-level="14.4.3" data-path="Chapter_14.html"><a href="Chapter_14.html#uniform-distribution"><i class="fa fa-check"></i><b>14.4.3</b> Uniform distribution</a></li>
<li class="chapter" data-level="14.4.4" data-path="Chapter_14.html"><a href="Chapter_14.html#normal-distribution"><i class="fa fa-check"></i><b>14.4.4</b> Normal distribution</a></li>
</ul></li>
<li class="chapter" data-level="14.5" data-path="Chapter_14.html"><a href="Chapter_14.html#summary-2"><i class="fa fa-check"></i><b>14.5</b> Summary</a></li>
</ul></li>
<li class="chapter" data-level="15" data-path="Chapter_15.html"><a href="Chapter_15.html"><i class="fa fa-check"></i><b>15</b> The Central Limit Theorem (CLT)</a>
<ul>
<li class="chapter" data-level="15.1" data-path="Chapter_15.html"><a href="Chapter_15.html#the-distribution-of-means-is-normal"><i class="fa fa-check"></i><b>15.1</b> The distribution of means is normal</a></li>
<li class="chapter" data-level="15.2" data-path="Chapter_15.html"><a href="Chapter_15.html#probability-and-z-scores"><i class="fa fa-check"></i><b>15.2</b> Probability and z-scores</a></li>
</ul></li>
<li class="chapter" data-level="16" data-path="Chapter_16.html"><a href="Chapter_16.html"><i class="fa fa-check"></i><b>16</b> <em>Practical</em>. Probability and simulation</a>
<ul>
<li class="chapter" data-level="16.1" data-path="Chapter_16.html"><a href="Chapter_16.html#probabilities-from-a-dataset"><i class="fa fa-check"></i><b>16.1</b> Probabilities from a dataset</a></li>
<li class="chapter" data-level="16.2" data-path="Chapter_16.html"><a href="Chapter_16.html#probabilities-from-a-normal-distribution"><i class="fa fa-check"></i><b>16.2</b> Probabilities from a normal distribution</a></li>
<li class="chapter" data-level="16.3" data-path="Chapter_16.html"><a href="Chapter_16.html#central-limit-theorem"><i class="fa fa-check"></i><b>16.3</b> Central limit theorem</a></li>
</ul></li>
<li class="part"><span><b>V Statistical inference</b></span></li>
<li class="chapter" data-level="" data-path="Week5.html"><a href="Week5.html"><i class="fa fa-check"></i>Week 5 Overview</a></li>
<li class="chapter" data-level="17" data-path="Chapter_17.html"><a href="Chapter_17.html"><i class="fa fa-check"></i><b>17</b> Confidence intervals (CIs)</a>
<ul>
<li class="chapter" data-level="17.1" data-path="Chapter_17.html"><a href="Chapter_17.html#normal-distribution-cis"><i class="fa fa-check"></i><b>17.1</b> Normal distribution CIs</a></li>
<li class="chapter" data-level="17.2" data-path="Chapter_17.html"><a href="Chapter_17.html#binomial-distribution-cis"><i class="fa fa-check"></i><b>17.2</b> Binomial distribution CIs</a></li>
</ul></li>
<li class="chapter" data-level="18" data-path="Chapter_18.html"><a href="Chapter_18.html"><i class="fa fa-check"></i><b>18</b> The t-interval</a></li>
<li class="chapter" data-level="19" data-path="Chapter_19.html"><a href="Chapter_19.html"><i class="fa fa-check"></i><b>19</b> <em>Practical</em>. z- and t- intervals</a>
<ul>
<li class="chapter" data-level="19.1" data-path="Chapter_19.html"><a href="Chapter_19.html#confidence-intervals-with-distraction"><i class="fa fa-check"></i><b>19.1</b> Confidence intervals with distrACTION</a></li>
<li class="chapter" data-level="19.2" data-path="Chapter_19.html"><a href="Chapter_19.html#confidence-intervals-from-z--and-t-scores"><i class="fa fa-check"></i><b>19.2</b> Confidence intervals from z- and t-scores</a></li>
<li class="chapter" data-level="19.3" data-path="Chapter_19.html"><a href="Chapter_19.html#confidence-intervals-for-different-sample-sizes-t--and-z-"><i class="fa fa-check"></i><b>19.3</b> Confidence intervals for different sample sizes (t- and z-)</a></li>
<li class="chapter" data-level="19.4" data-path="Chapter_19.html"><a href="Chapter_19.html#proportion-confidence-intervals"><i class="fa fa-check"></i><b>19.4</b> Proportion confidence intervals</a></li>
<li class="chapter" data-level="19.5" data-path="Chapter_19.html"><a href="Chapter_19.html#another-proportion-confidence-interval"><i class="fa fa-check"></i><b>19.5</b> Another proportion confidence interval</a></li>
</ul></li>
<li class="part"><span><b>VI Hypothesis testing</b></span></li>
<li class="chapter" data-level="" data-path="Week6.html"><a href="Week6.html"><i class="fa fa-check"></i>Week 6 Overview</a></li>
<li class="chapter" data-level="20" data-path="Chapter_20.html"><a href="Chapter_20.html"><i class="fa fa-check"></i><b>20</b> What is hypothesis testing?</a>
<ul>
<li class="chapter" data-level="20.1" data-path="Chapter_20.html"><a href="Chapter_20.html#how-ridiculous-is-our-hypothesis"><i class="fa fa-check"></i><b>20.1</b> How ridiculous is our hypothesis?</a></li>
<li class="chapter" data-level="20.2" data-path="Chapter_20.html"><a href="Chapter_20.html#statistical-hypothesis-testing"><i class="fa fa-check"></i><b>20.2</b> Statistical hypothesis testing</a></li>
<li class="chapter" data-level="20.3" data-path="Chapter_20.html"><a href="Chapter_20.html#p-values-false-positives-and-power"><i class="fa fa-check"></i><b>20.3</b> P-values, false positives, and power</a></li>
</ul></li>
<li class="chapter" data-level="21" data-path="Chapter_21.html"><a href="Chapter_21.html"><i class="fa fa-check"></i><b>21</b> The t-test</a>
<ul>
<li class="chapter" data-level="21.1" data-path="Chapter_21.html"><a href="Chapter_21.html#one-sample-t-test"><i class="fa fa-check"></i><b>21.1</b> One sample t-test</a></li>
<li class="chapter" data-level="21.2" data-path="Chapter_21.html"><a href="Chapter_21.html#independent-samples-t-test"><i class="fa fa-check"></i><b>21.2</b> Independent samples t-test</a></li>
<li class="chapter" data-level="21.3" data-path="Chapter_21.html"><a href="Chapter_21.html#paired-sample-t-test"><i class="fa fa-check"></i><b>21.3</b> Paired sample t-test</a></li>
<li class="chapter" data-level="21.4" data-path="Chapter_21.html"><a href="Chapter_21.html#assumptions-of-t-tests"><i class="fa fa-check"></i><b>21.4</b> Assumptions of t-tests</a></li>
<li class="chapter" data-level="21.5" data-path="Chapter_21.html"><a href="Chapter_21.html#non-parametric-alternatives"><i class="fa fa-check"></i><b>21.5</b> Non-parametric alternatives</a>
<ul>
<li class="chapter" data-level="21.5.1" data-path="Chapter_21.html"><a href="Chapter_21.html#wilcoxon-test"><i class="fa fa-check"></i><b>21.5.1</b> Wilcoxon test</a></li>
<li class="chapter" data-level="21.5.2" data-path="Chapter_21.html"><a href="Chapter_21.html#mann-whitney-u-test"><i class="fa fa-check"></i><b>21.5.2</b> Mann-Whitney U test</a></li>
</ul></li>
<li class="chapter" data-level="21.6" data-path="Chapter_21.html"><a href="Chapter_21.html#summary-3"><i class="fa fa-check"></i><b>21.6</b> Summary</a></li>
</ul></li>
<li class="chapter" data-level="22" data-path="Chapter_22.html"><a href="Chapter_22.html"><i class="fa fa-check"></i><b>22</b> <em>Practical</em>. Hypothesis testing and t-tests</a>
<ul>
<li class="chapter" data-level="22.1" data-path="Chapter_22.html"><a href="Chapter_22.html#exercise-on-a-simple-one-sample-t-test"><i class="fa fa-check"></i><b>22.1</b> Exercise on a simple one sample t-test</a></li>
<li class="chapter" data-level="22.2" data-path="Chapter_22.html"><a href="Chapter_22.html#exercise-on-a-paired-t-test"><i class="fa fa-check"></i><b>22.2</b> Exercise on a paired t-test</a></li>
<li class="chapter" data-level="22.3" data-path="Chapter_22.html"><a href="Chapter_22.html#wilcoxon-test-1"><i class="fa fa-check"></i><b>22.3</b> Wilcoxon test</a></li>
<li class="chapter" data-level="22.4" data-path="Chapter_22.html"><a href="Chapter_22.html#independent-samples-t-test-1"><i class="fa fa-check"></i><b>22.4</b> Independent samples t-test</a></li>
<li class="chapter" data-level="22.5" data-path="Chapter_22.html"><a href="Chapter_22.html#mann-whitney-u-test-1"><i class="fa fa-check"></i><b>22.5</b> Mann-Whitney U Test</a></li>
</ul></li>
<li class="part"><span><b>VII Review of parts I-V</b></span></li>
<li class="chapter" data-level="" data-path="Week7.html"><a href="Week7.html"><i class="fa fa-check"></i>Week 7 Overview (Reading week)</a></li>
<li class="part"><span><b>VIII Analysis of Variance (ANOVA)</b></span></li>
<li class="chapter" data-level="" data-path="Week8.html"><a href="Week8.html"><i class="fa fa-check"></i>Week 8 Overview</a></li>
<li class="chapter" data-level="23" data-path="Chapter_23.html"><a href="Chapter_23.html"><i class="fa fa-check"></i><b>23</b> Analysis of variance</a>
<ul>
<li class="chapter" data-level="23.1" data-path="Chapter_23.html"><a href="Chapter_23.html#the-f-distribution"><i class="fa fa-check"></i><b>23.1</b> The F-distribution</a></li>
<li class="chapter" data-level="23.2" data-path="Chapter_23.html"><a href="Chapter_23.html#one-way-anova"><i class="fa fa-check"></i><b>23.2</b> One-way ANOVA</a>
<ul>
<li class="chapter" data-level="23.2.1" data-path="Chapter_23.html"><a href="Chapter_23.html#anova-mean-variance-among-groups"><i class="fa fa-check"></i><b>23.2.1</b> ANOVA mean variance among groups</a></li>
<li class="chapter" data-level="23.2.2" data-path="Chapter_23.html"><a href="Chapter_23.html#anova-mean-variance-within-groups"><i class="fa fa-check"></i><b>23.2.2</b> ANOVA mean variance within groups</a></li>
<li class="chapter" data-level="23.2.3" data-path="Chapter_23.html"><a href="Chapter_23.html#anova-f-statistic-calculation"><i class="fa fa-check"></i><b>23.2.3</b> ANOVA F statistic calculation</a></li>
</ul></li>
<li class="chapter" data-level="23.3" data-path="Chapter_23.html"><a href="Chapter_23.html#assumptions-of-anova"><i class="fa fa-check"></i><b>23.3</b> Assumptions of ANOVA</a></li>
</ul></li>
<li class="chapter" data-level="24" data-path="Chapter_24.html"><a href="Chapter_24.html"><i class="fa fa-check"></i><b>24</b> Multiple comparisons</a></li>
<li class="chapter" data-level="25" data-path="Chapter_25.html"><a href="Chapter_25.html"><i class="fa fa-check"></i><b>25</b> Kruskall-Wallis H test</a></li>
<li class="chapter" data-level="26" data-path="Chapter_26.html"><a href="Chapter_26.html"><i class="fa fa-check"></i><b>26</b> Two-way ANOVA</a></li>
<li class="chapter" data-level="27" data-path="Chapter_27.html"><a href="Chapter_27.html"><i class="fa fa-check"></i><b>27</b> <em>Practical</em>. ANOVA and associated tests</a>
<ul>
<li class="chapter" data-level="27.1" data-path="Chapter_27.html"><a href="Chapter_27.html#one-way-anova-site"><i class="fa fa-check"></i><b>27.1</b> One-way ANOVA (site)</a></li>
<li class="chapter" data-level="27.2" data-path="Chapter_27.html"><a href="Chapter_27.html#one-way-anova-profile"><i class="fa fa-check"></i><b>27.2</b> One-way ANOVA (profile)</a></li>
<li class="chapter" data-level="27.3" data-path="Chapter_27.html"><a href="Chapter_27.html#multiple-comparisons"><i class="fa fa-check"></i><b>27.3</b> Multiple comparisons</a></li>
<li class="chapter" data-level="27.4" data-path="Chapter_27.html"><a href="Chapter_27.html#kruskall-wallis-h-test"><i class="fa fa-check"></i><b>27.4</b> Kruskall-Wallis H test</a></li>
<li class="chapter" data-level="27.5" data-path="Chapter_27.html"><a href="Chapter_27.html#two-way-anova"><i class="fa fa-check"></i><b>27.5</b> Two-way ANOVA</a></li>
</ul></li>
<li class="part"><span><b>IX Counts and Correlation</b></span></li>
<li class="chapter" data-level="" data-path="Week9.html"><a href="Week9.html"><i class="fa fa-check"></i>Week 9 Overview</a></li>
<li class="chapter" data-level="28" data-path="Chapter_28.html"><a href="Chapter_28.html"><i class="fa fa-check"></i><b>28</b> Frequency and count data</a>
<ul>
<li class="chapter" data-level="28.1" data-path="Chapter_28.html"><a href="Chapter_28.html#the-chi-square-distribution"><i class="fa fa-check"></i><b>28.1</b> The Chi-square distribution</a></li>
<li class="chapter" data-level="28.2" data-path="Chapter_28.html"><a href="Chapter_28.html#chi-squared-goodness-of-fit"><i class="fa fa-check"></i><b>28.2</b> Chi-squared goodness of fit</a></li>
<li class="chapter" data-level="28.3" data-path="Chapter_28.html"><a href="Chapter_28.html#chi-squared-test-of-association"><i class="fa fa-check"></i><b>28.3</b> Chi-squared test of association</a></li>
</ul></li>
<li class="chapter" data-level="29" data-path="Chapter_29.html"><a href="Chapter_29.html"><i class="fa fa-check"></i><b>29</b> Correlation</a>
<ul>
<li class="chapter" data-level="29.1" data-path="Chapter_29.html"><a href="Chapter_29.html#scatterplots"><i class="fa fa-check"></i><b>29.1</b> Scatterplots</a></li>
<li class="chapter" data-level="29.2" data-path="Chapter_29.html"><a href="Chapter_29.html#the-correlation-coefficient"><i class="fa fa-check"></i><b>29.2</b> The correlation coefficient</a>
<ul>
<li class="chapter" data-level="29.2.1" data-path="Chapter_29.html"><a href="Chapter_29.html#pearson-product-moment-correlation-coefficient"><i class="fa fa-check"></i><b>29.2.1</b> Pearson product moment correlation coefficient</a></li>
<li class="chapter" data-level="29.2.2" data-path="Chapter_29.html"><a href="Chapter_29.html#spearman-rank-correlation-coefficient"><i class="fa fa-check"></i><b>29.2.2</b> Spearman rank correlation coefficient</a></li>
</ul></li>
<li class="chapter" data-level="29.3" data-path="Chapter_29.html"><a href="Chapter_29.html#correlation-hypothesis-testing"><i class="fa fa-check"></i><b>29.3</b> Correlation hypothesis testing</a></li>
</ul></li>
<li class="chapter" data-level="30" data-path="Chapter_30.html"><a href="Chapter_30.html"><i class="fa fa-check"></i><b>30</b> <em>Practical</em>. Analysis of counts and correlations</a>
<ul>
<li class="chapter" data-level="30.1" data-path="Chapter_30.html"><a href="Chapter_30.html#survival-goodness-of-fit"><i class="fa fa-check"></i><b>30.1</b> Survival goodness of fit</a></li>
<li class="chapter" data-level="30.2" data-path="Chapter_30.html"><a href="Chapter_30.html#colony-goodness-of-fit"><i class="fa fa-check"></i><b>30.2</b> Colony goodness of fit</a></li>
<li class="chapter" data-level="30.3" data-path="Chapter_30.html"><a href="Chapter_30.html#chi-square-test-of-association"><i class="fa fa-check"></i><b>30.3</b> Chi-Square test of association</a></li>
<li class="chapter" data-level="30.4" data-path="Chapter_30.html"><a href="Chapter_30.html#pearson-product-moment-correlation-test"><i class="fa fa-check"></i><b>30.4</b> Pearson product moment correlation test</a></li>
<li class="chapter" data-level="30.5" data-path="Chapter_30.html"><a href="Chapter_30.html#spearman-rank-correlation-test"><i class="fa fa-check"></i><b>30.5</b> Spearman rank correlation test</a></li>
<li class="chapter" data-level="30.6" data-path="Chapter_30.html"><a href="Chapter_30.html#untidy-goodness-of-fit"><i class="fa fa-check"></i><b>30.6</b> Untidy goodness of fit</a></li>
</ul></li>
<li class="part"><span><b>X Linear Regression</b></span></li>
<li class="chapter" data-level="" data-path="Week10.html"><a href="Week10.html"><i class="fa fa-check"></i>Week 10 Overview</a></li>
<li class="chapter" data-level="31" data-path="Chapter_31.html"><a href="Chapter_31.html"><i class="fa fa-check"></i><b>31</b> Simple linear regression</a>
<ul>
<li class="chapter" data-level="31.1" data-path="Chapter_31.html"><a href="Chapter_31.html#visual-interpretation-of-regression"><i class="fa fa-check"></i><b>31.1</b> Visual interpretation of regression</a></li>
<li class="chapter" data-level="31.2" data-path="Chapter_31.html"><a href="Chapter_31.html#intercepts-slopes-and-residuals"><i class="fa fa-check"></i><b>31.2</b> Intercepts, slopes, and residuals</a></li>
<li class="chapter" data-level="31.3" data-path="Chapter_31.html"><a href="Chapter_31.html#regression-coefficients"><i class="fa fa-check"></i><b>31.3</b> Regression coefficients</a></li>
<li class="chapter" data-level="31.4" data-path="Chapter_31.html"><a href="Chapter_31.html#regression-line-calculation"><i class="fa fa-check"></i><b>31.4</b> Regression line calculation</a></li>
<li class="chapter" data-level="31.5" data-path="Chapter_31.html"><a href="Chapter_31.html#coefficient-of-determination"><i class="fa fa-check"></i><b>31.5</b> Coefficient of determination</a></li>
<li class="chapter" data-level="31.6" data-path="Chapter_31.html"><a href="Chapter_31.html#regression-assumptions"><i class="fa fa-check"></i><b>31.6</b> Regression assumptions</a></li>
<li class="chapter" data-level="31.7" data-path="Chapter_31.html"><a href="Chapter_31.html#regression-hypothesis-testing"><i class="fa fa-check"></i><b>31.7</b> Regression hypothesis testing</a>
<ul>
<li class="chapter" data-level="31.7.1" data-path="Chapter_31.html"><a href="Chapter_31.html#overall-model-significance"><i class="fa fa-check"></i><b>31.7.1</b> Overall model significance</a></li>
<li class="chapter" data-level="31.7.2" data-path="Chapter_31.html"><a href="Chapter_31.html#significance-of-the-intercept"><i class="fa fa-check"></i><b>31.7.2</b> Significance of the intercept</a></li>
<li class="chapter" data-level="31.7.3" data-path="Chapter_31.html"><a href="Chapter_31.html#significance-of-the-slope"><i class="fa fa-check"></i><b>31.7.3</b> Significance of the slope</a></li>
<li class="chapter" data-level="31.7.4" data-path="Chapter_31.html"><a href="Chapter_31.html#simple-regression-output"><i class="fa fa-check"></i><b>31.7.4</b> Simple regression output</a></li>
</ul></li>
<li class="chapter" data-level="31.8" data-path="Chapter_31.html"><a href="Chapter_31.html#prediction-with-linear-models"><i class="fa fa-check"></i><b>31.8</b> Prediction with linear models</a></li>
<li class="chapter" data-level="31.9" data-path="Chapter_31.html"><a href="Chapter_31.html#conclusion"><i class="fa fa-check"></i><b>31.9</b> Conclusion</a></li>
</ul></li>
<li class="chapter" data-level="32" data-path="Chapter_32.html"><a href="Chapter_32.html"><i class="fa fa-check"></i><b>32</b> Multiple regression</a>
<ul>
<li class="chapter" data-level="32.1" data-path="Chapter_32.html"><a href="Chapter_32.html#adjusted-coefficient-of-determination"><i class="fa fa-check"></i><b>32.1</b> Adjusted coefficient of determination</a></li>
</ul></li>
<li class="chapter" data-level="33" data-path="Chapter_33.html"><a href="Chapter_33.html"><i class="fa fa-check"></i><b>33</b> <em>Practical</em>. Using regression</a>
<ul>
<li class="chapter" data-level="33.1" data-path="Chapter_33.html"><a href="Chapter_33.html#predicting-pyrogenic-carbon-from-soil-depth"><i class="fa fa-check"></i><b>33.1</b> Predicting pyrogenic carbon from soil depth</a></li>
<li class="chapter" data-level="33.2" data-path="Chapter_33.html"><a href="Chapter_33.html#predicting-pyrogenic-carbon-from-fire-frequency"><i class="fa fa-check"></i><b>33.2</b> Predicting pyrogenic carbon from fire frequency</a></li>
<li class="chapter" data-level="33.3" data-path="Chapter_33.html"><a href="Chapter_33.html#multiple-regression-depth-and-fire-frequency"><i class="fa fa-check"></i><b>33.3</b> Multiple regression depth and fire frequency</a></li>
<li class="chapter" data-level="33.4" data-path="Chapter_33.html"><a href="Chapter_33.html#large-multiple-regression"><i class="fa fa-check"></i><b>33.4</b> Large multiple regression</a></li>
<li class="chapter" data-level="33.5" data-path="Chapter_33.html"><a href="Chapter_33.html#predicting-temperature-from-fire-frequency"><i class="fa fa-check"></i><b>33.5</b> Predicting temperature from fire frequency</a></li>
</ul></li>
<li class="part"><span><b>XI Randomisation approaches</b></span></li>
<li class="chapter" data-level="" data-path="Week11.html"><a href="Week11.html"><i class="fa fa-check"></i>Week 11 Overview</a></li>
<li class="chapter" data-level="34" data-path="Chapter_34.html"><a href="Chapter_34.html"><i class="fa fa-check"></i><b>34</b> Randomisation</a>
<ul>
<li class="chapter" data-level="34.1" data-path="Chapter_34.html"><a href="Chapter_34.html#summary-of-parametric-hypothesis-testing"><i class="fa fa-check"></i><b>34.1</b> Summary of parametric hypothesis testing</a></li>
<li class="chapter" data-level="34.2" data-path="Chapter_34.html"><a href="Chapter_34.html#randomisation-approach"><i class="fa fa-check"></i><b>34.2</b> Randomisation approach</a></li>
<li class="chapter" data-level="34.3" data-path="Chapter_34.html"><a href="Chapter_34.html#randomisation-for-hypothesis-testing"><i class="fa fa-check"></i><b>34.3</b> Randomisation for hypothesis testing</a></li>
<li class="chapter" data-level="34.4" data-path="Chapter_34.html"><a href="Chapter_34.html#randomisation-assumptions"><i class="fa fa-check"></i><b>34.4</b> Randomisation assumptions</a></li>
<li class="chapter" data-level="34.5" data-path="Chapter_34.html"><a href="Chapter_34.html#bootstrapping"><i class="fa fa-check"></i><b>34.5</b> Bootstrapping</a></li>
<li class="chapter" data-level="34.6" data-path="Chapter_34.html"><a href="Chapter_34.html#monte-carlo"><i class="fa fa-check"></i><b>34.6</b> Monte Carlo</a></li>
<li class="chapter" data-level="34.7" data-path="Chapter_34.html"><a href="Chapter_34.html#randomisation-conclusions"><i class="fa fa-check"></i><b>34.7</b> Randomisation conclusions</a></li>
</ul></li>
<li class="chapter" data-level="35" data-path="Chapter_35.html"><a href="Chapter_35.html"><i class="fa fa-check"></i><b>35</b> <em>Practical</em>. Using R</a>
<ul>
<li class="chapter" data-level="35.1" data-path="Chapter_35.html"><a href="Chapter_35.html#getting-used-to-the-r-interface"><i class="fa fa-check"></i><b>35.1</b> Getting used to the R interface</a></li>
<li class="chapter" data-level="35.2" data-path="Chapter_35.html"><a href="Chapter_35.html#assigning-variables-in-the-r-console"><i class="fa fa-check"></i><b>35.2</b> Assigning variables in the R console</a></li>
<li class="chapter" data-level="35.3" data-path="Chapter_35.html"><a href="Chapter_35.html#some-descriptive-statistics"><i class="fa fa-check"></i><b>35.3</b> Some descriptive statistics</a></li>
<li class="chapter" data-level="35.4" data-path="Chapter_35.html"><a href="Chapter_35.html#bootstrapping-confidence-intervals"><i class="fa fa-check"></i><b>35.4</b> Bootstrapping confidence intervals</a></li>
</ul></li>
<li class="part"><span><b>XII Statistical Reporting</b></span></li>
<li class="chapter" data-level="" data-path="Week12.html"><a href="Week12.html"><i class="fa fa-check"></i>Week 12 Overview</a></li>
<li class="chapter" data-level="36" data-path="reporting-statistics.html"><a href="reporting-statistics.html"><i class="fa fa-check"></i><b>36</b> Reporting statistics</a>
<ul>
<li class="chapter" data-level="36.1" data-path="reporting-statistics.html"><a href="reporting-statistics.html#before-collecting-data"><i class="fa fa-check"></i><b>36.1</b> Before collecting data</a></li>
<li class="chapter" data-level="36.2" data-path="reporting-statistics.html"><a href="reporting-statistics.html#statistical-reporting"><i class="fa fa-check"></i><b>36.2</b> Statistical reporting</a>
<ul>
<li class="chapter" data-level="36.2.1" data-path="reporting-statistics.html"><a href="reporting-statistics.html#abstract"><i class="fa fa-check"></i><b>36.2.1</b> Abstract</a></li>
<li class="chapter" data-level="36.2.2" data-path="reporting-statistics.html"><a href="reporting-statistics.html#introduction"><i class="fa fa-check"></i><b>36.2.2</b> Introduction</a></li>
<li class="chapter" data-level="36.2.3" data-path="reporting-statistics.html"><a href="reporting-statistics.html#methods"><i class="fa fa-check"></i><b>36.2.3</b> Methods</a></li>
<li class="chapter" data-level="36.2.4" data-path="reporting-statistics.html"><a href="reporting-statistics.html#results"><i class="fa fa-check"></i><b>36.2.4</b> Results</a></li>
<li class="chapter" data-level="36.2.5" data-path="reporting-statistics.html"><a href="reporting-statistics.html#discussion"><i class="fa fa-check"></i><b>36.2.5</b> Discussion</a></li>
</ul></li>
<li class="chapter" data-level="36.3" data-path="reporting-statistics.html"><a href="reporting-statistics.html#figures-and-tables"><i class="fa fa-check"></i><b>36.3</b> Figures and tables</a>
<ul>
<li class="chapter" data-level="36.3.1" data-path="reporting-statistics.html"><a href="reporting-statistics.html#figures"><i class="fa fa-check"></i><b>36.3.1</b> Figures</a></li>
<li class="chapter" data-level="36.3.2" data-path="reporting-statistics.html"><a href="reporting-statistics.html#tables"><i class="fa fa-check"></i><b>36.3.2</b> Tables</a></li>
</ul></li>
<li class="chapter" data-level="36.4" data-path="reporting-statistics.html"><a href="reporting-statistics.html#statistical-tests"><i class="fa fa-check"></i><b>36.4</b> Statistical tests</a>
<ul>
<li class="chapter" data-level="36.4.1" data-path="reporting-statistics.html"><a href="reporting-statistics.html#reporting-t-tests"><i class="fa fa-check"></i><b>36.4.1</b> Reporting t-tests</a></li>
<li class="chapter" data-level="36.4.2" data-path="reporting-statistics.html"><a href="reporting-statistics.html#reporting-anova"><i class="fa fa-check"></i><b>36.4.2</b> Reporting ANOVA</a></li>
<li class="chapter" data-level="36.4.3" data-path="reporting-statistics.html"><a href="reporting-statistics.html#reporting-a-main-whitney-u-test"><i class="fa fa-check"></i><b>36.4.3</b> Reporting a Main-Whitney U test</a></li>
<li class="chapter" data-level="36.4.4" data-path="reporting-statistics.html"><a href="reporting-statistics.html#reporting-a-wilcoxon-signed-rank-test"><i class="fa fa-check"></i><b>36.4.4</b> Reporting a Wilcoxon signed-rank test</a></li>
<li class="chapter" data-level="36.4.5" data-path="reporting-statistics.html"><a href="reporting-statistics.html#reporting-chi-square-tests"><i class="fa fa-check"></i><b>36.4.5</b> Reporting Chi-square tests</a></li>
<li class="chapter" data-level="36.4.6" data-path="reporting-statistics.html"><a href="reporting-statistics.html#reporting-correlation-coefficients"><i class="fa fa-check"></i><b>36.4.6</b> Reporting correlation coefficients</a></li>
<li class="chapter" data-level="36.4.7" data-path="reporting-statistics.html"><a href="reporting-statistics.html#reporting-regressions"><i class="fa fa-check"></i><b>36.4.7</b> Reporting regressions</a></li>
</ul></li>
<li class="chapter" data-level="36.5" data-path="reporting-statistics.html"><a href="reporting-statistics.html#conclusions"><i class="fa fa-check"></i><b>36.5</b> Conclusions</a></li>
</ul></li>
<li class="chapter" data-level="37" data-path="practical.-using-r.html"><a href="practical.-using-r.html"><i class="fa fa-check"></i><b>37</b> <em>Practical</em>. Using R</a>
<ul>
<li class="chapter" data-level="37.1" data-path="practical.-using-r.html"><a href="practical.-using-r.html#working-with-a-data-set"><i class="fa fa-check"></i><b>37.1</b> Working with a data set</a></li>
<li class="chapter" data-level="37.2" data-path="practical.-using-r.html"><a href="practical.-using-r.html#familiar-statistical-tests-in-r"><i class="fa fa-check"></i><b>37.2</b> Familiar statistical tests in R</a>
<ul>
<li class="chapter" data-level="37.2.1" data-path="practical.-using-r.html"><a href="practical.-using-r.html#one-way-anova-in-r"><i class="fa fa-check"></i><b>37.2.1</b> One-way ANOVA in R</a></li>
<li class="chapter" data-level="37.2.2" data-path="practical.-using-r.html"><a href="practical.-using-r.html#two-way-anova-in-r"><i class="fa fa-check"></i><b>37.2.2</b> Two-way ANOVA in R</a></li>
<li class="chapter" data-level="37.2.3" data-path="practical.-using-r.html"><a href="practical.-using-r.html#chi-square-test-in-r"><i class="fa fa-check"></i><b>37.2.3</b> Chi-square test in R</a></li>
</ul></li>
<li class="chapter" data-level="37.3" data-path="practical.-using-r.html"><a href="practical.-using-r.html#reading-and-writing-data-in-r"><i class="fa fa-check"></i><b>37.3</b> Reading and writing data in R</a></li>
<li class="chapter" data-level="37.4" data-path="practical.-using-r.html"><a href="practical.-using-r.html#appendix"><i class="fa fa-check"></i><b>37.4</b> Appendix</a></li>
</ul></li>
<li class="part"><span><b>XIII Review of parts (VII-XII)</b></span></li>
<li class="chapter" data-level="" data-path="Week13.html"><a href="Week13.html"><i class="fa fa-check"></i>Module summary</a></li>
<li class="appendix"><span><b>Appendix</b></span></li>
<li class="chapter" data-level="A" data-path="appendexA_CMS.html"><a href="appendexA_CMS.html"><i class="fa fa-check"></i><b>A</b> Common Marking Scheme</a></li>
<li class="chapter" data-level="B" data-path="uncertainty_derivation.html"><a href="uncertainty_derivation.html"><i class="fa fa-check"></i><b>B</b> Uncertainty derivation</a></li>
<li class="chapter" data-level="C" data-path="appendixC_tables.html"><a href="appendixC_tables.html"><i class="fa fa-check"></i><b>C</b> Statistical tables</a>
<ul>
<li class="chapter" data-level="C.1" data-path="appendixC_tables.html"><a href="appendixC_tables.html#wilcoxon-signed-rank-critical-values"><i class="fa fa-check"></i><b>C.1</b> Wilcoxon signed rank critical values</a></li>
<li class="chapter" data-level="C.2" data-path="appendixC_tables.html"><a href="appendixC_tables.html#mann-whitney-u-critical-values"><i class="fa fa-check"></i><b>C.2</b> Mann-Whitney U critical values</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="references.html"><a href="references.html"><i class="fa fa-check"></i>References</a></li>
<li class="divider"></li>
<li><a href="https://github.com/rstudio/bookdown" target="blank">Published with bookdown</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Statistical Techniques for Biological and Environmental Sciences</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="practical.-using-r" class="section level1 hasAnchor" number="37">
<h1><span class="header-section-number">Chapter 37</span> <em>Practical</em>. Using R<a href="practical.-using-r.html#practical.-using-r" class="anchor-section" aria-label="Anchor link to header"></a></h1>
<p>This lab practical will demonstrate how to run statistical tests in R that have been introduced in Jamovi in previous practicals.
The practical will use the <a href="https://allisonhorst.github.io/palmerpenguins/articles/intro.html#package-citation-1">PalmerPenguins</a> dataset <span class="citation">(<a href="#ref-GormanEtAl2014" role="doc-biblioref">Gorman, Williams, and Fraser 2014</a>; <a href="#ref-HorstEtAl2020" role="doc-biblioref">Horst, Hill, and Gorman 2020</a>)</span>.
These data include morphological measurements for 3 species of penguins that inhabit 3 islands in the Palmer Archipelago, Antarctica (Figure 37.1; artwork by <a href="https://allisonhorst.com/">allison_horst</a>, Creative Commons Attribution 4.0 International License).</p>
<div class="figure"><span style="display:block;" id="fig:unnamed-chunk-217"></span>
<img src="img/penguins.png" alt="Cartoon image of three penguins standing in a row, each highlighted by a background of a different colour." width="100%" />
<p class="caption">
Figure 37.1: This practical uses data collected on the morphologies of 3 Antarctic penguin species.
</p>
</div>
<p>The data were collected by Dr Kristen Gorman at the <a href="https://pal.lternet.edu/">Palmer Station</a> Long Term Ecological Research program from 2007-2009.
To complete this lab, download the <a href="https://raw.githubusercontent.com/bradduthie/SCIU4T4/main/data/penguins.csv">penguins.csv</a> dataset (right click and “Save Link As…”, then save it with the extension ‘.csv’).
Data include measurements of bill length (mm), bill depth (mm), flipper length (mm), body mass (g), and sampling year for penguins of 3 species on 3 islands.</p>
<div id="working-with-a-data-set" class="section level2 hasAnchor" number="37.1">
<h2><span class="header-section-number">37.1</span> Working with a data set<a href="practical.-using-r.html#working-with-a-data-set" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>First, we need to open Rstudio.
You can do this on your own computer, or within a browser on the <a href="https://posit.cloud/">posit cloud</a>.
Although it is possible to use R in a different environment than Rstudio, Rstudio will make some tasks easier.
To get started, we need to make that we are working in the same directory (i.e., folder, see <a href="Chapter_2.html#managing-data-files">Chapter 2.3</a> on managing data files) that we saved the <a href="https://raw.githubusercontent.com/bradduthie/SCIU4T4/main/data/penguins.csv">penguins.csv</a>.
We could use the <code>setwd()</code> function to do this (e.g., by typing something like <code>setwd("C:\Users\MyName\Documents")</code> in the console on a Windows computer).
But the easiest way in Rstudio is to navigate to the toolbar and select ‘Session’, then ‘Set Working Directory’ from the pulldown, and then ‘Choose Directory’ (Figure 37.2).</p>
<div class="figure"><span style="display:block;" id="fig:unnamed-chunk-218"></span>
<img src="img/Rstudio_setwd.png" alt="Rstudio menu is show with 'Session' selected from the toolbar, then 'Set Working Directory' from the pull down, which opens another pulldown with the highlighted option 'Choose Directory'." width="100%" />
<p class="caption">
Figure 37.2: Rstudio option in the toolbar for setting a working directory.
</p>
</div>
<p>A new window will open that will allow you to navigate to the location in which <a href="https://raw.githubusercontent.com/bradduthie/SCIU4T4/main/data/penguins.csv">penguins.csv</a> was saved.</p>
<p>In the practical from <a href="Chapter_35.html#Chapter_35">Chapter 35</a>, we worked entirely from the R console.
This time, we will will introduce R scripts to make organising the code a bit easier.
To do this, navigate to the Rstudio toolbar and select ‘File’, then ‘New File’ followed by ‘R Script’ (Figure 37.3).</p>
<div class="figure"><span style="display:block;" id="fig:unnamed-chunk-219"></span>
<img src="img/Rstudio_script.png" alt="Rstudio menu is show with 'File' selected from the toolbar, then 'New File' from the pull down, which opens another pulldown with the highlighted option 'R script'." width="100%" />
<p class="caption">
Figure 37.3: Rstudio option in the toolbar for creating a new R script.
</p>
</div>
<p>You should then see an empty script called ‘Untitled1’ open up above the R console.
This will be useful because it will allow us to save the R commands that we run.</p>
<blockquote>
<p>Task 1: Open a new R script by selecting ‘File &gt; New File &gt; R script’.</p>
</blockquote>
<p>Now we need to read in the penguins dataset.
Assuming that we are in the same working directory as the place we saved the file called ‘penguins.csv’, we can use the function <code>read.csv</code> to read in the CSV file.
Type (or copy-paste) the line below into the R script.</p>
<div class="sourceCode" id="cb159"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb159-1"><a href="practical.-using-r.html#cb159-1" aria-hidden="true" tabindex="-1"></a>penguins <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="at">file =</span> <span class="st">&quot;penguins.csv&quot;</span>);</span></code></pre></div>
<p>Put your cursor on the line that you typed (you can also highlight the whole line, but this is not necessary).
Next, find the ‘Run’ button in the toolbar and click it (Figure 37.4).
Rstudio will run whatever line of code your cursor is on, or whatever chunk of code is highlighted (including multiple lines at once; notice the line numbers in the left margin of the script).</p>
<div class="figure"><span style="display:block;" id="fig:unnamed-chunk-222"></span>
<img src="img/Rstudio_run.png" alt="Rstudio toolbar is shown with multiple options, including one that says 'Run' in the upper right." width="100%" />
<p class="caption">
Figure 37.4: An Rstudio toolbar with the ‘Run’ option in the upper right to run a line of code from the script to the console.
</p>
</div>
<p>If that did not work, then double-check to make sure that you are in the correct directory and have the file name correct.
Everything in R is case sensitive, meaning that capitalisation matters, so R will treat ‘Penguins.csv’ and ‘penguins.csv’ as completely different!
It is important to be precise.</p>
<p>Once you have read in the penguins dataset, have a look at the first 6 rows using the function <code>head</code>.</p>
<blockquote>
<p>Task 2: View the first 6 rows of the penguins dataset.</p>
</blockquote>
<p>On the second line of your R script, type the code below, then run it.</p>
<div class="sourceCode" id="cb160"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb160-1"><a href="practical.-using-r.html#cb160-1" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(penguins);</span></code></pre></div>
<pre><code>  species    island bill_length bill_depth flipper_length mass  year
1  Adelie Torgersen        39.1       18.7            181 3750 Y2007
2  Adelie Torgersen        39.5       17.4            186 3800 Y2007
3  Adelie Torgersen        40.3       18.0            195 3250 Y2007
4  Adelie Torgersen          NA         NA             NA   NA Y2007
5  Adelie Torgersen        36.7       19.3            193 3450 Y2007
6  Adelie Torgersen        39.3       20.6            190 3650 Y2007</code></pre>
<p>You should see the first 6 rows of the dataset print out in the console.
Notice that the dataset is already in a tidy format.
Each row is an individual penguin, and each variable is a column.</p>
<p>Unlike Jamovi, we cannot change the data in penguins simply by clicking on values.
Like everything else in R, we need to do this using code.
If we wanted to change the value of row one column three to 40, for example (i.e., the first penguin’s bill depth), then we would need to do the following.</p>
<div class="sourceCode" id="cb162"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb162-1"><a href="practical.-using-r.html#cb162-1" aria-hidden="true" tabindex="-1"></a>penguins[<span class="dv">1</span>, <span class="dv">3</span>] <span class="ot">&lt;-</span> <span class="dv">40</span></span></code></pre></div>
<p>The square brackets can be used to indicate a specific row and column in the data (i.e., data[row_number, column_number]).
A missing value in the square brackets will be interpreted by R as referring to all elements in the dataset.
For example, if we wanted to have R just print off the fifth row of the penguins dataset, we could run the following.</p>
<div class="sourceCode" id="cb163"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb163-1"><a href="practical.-using-r.html#cb163-1" aria-hidden="true" tabindex="-1"></a>penguins[<span class="dv">5</span>, ]</span></code></pre></div>
<p>The absence of any value above in <code>, ]</code> tells R to print all of the columns. We can do the same for the columns.</p>
<blockquote>
<p>Task 3: Print just column 3 of the penguins dataset. What does the code look like?</p>
</blockquote>
<p>Code to return column 3: ______________________________________</p>
<p>Notice that some of the values in the dataset are not numeric, but instead are given as <code>NA</code>.
This is how missing data are indicated in R.
An example of this is shown in the measurements for the penguin in the fourth row.
These <code>NA</code> values can become a nuisance when we try to calculate summary statistics.
Using the <code>mean</code> function introduced in the practical last week, try running the line of code below to get the mean of column 3.</p>
<div class="sourceCode" id="cb164"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb164-1"><a href="practical.-using-r.html#cb164-1" aria-hidden="true" tabindex="-1"></a><span class="fu">mean</span>(<span class="at">x =</span> penguins[,<span class="dv">3</span>])</span></code></pre></div>
<p>We get a value of <code>NA</code> instead of the mean of the numbers that are not missing.
This is because we need to tell R explicitly to remove values that are missing when calculating the mean.
We can do this with the <code>na.rm</code> argument in the mean function.</p>
<div class="sourceCode" id="cb165"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb165-1"><a href="practical.-using-r.html#cb165-1" aria-hidden="true" tabindex="-1"></a><span class="fu">mean</span>(<span class="at">x =</span> penguins[,<span class="dv">3</span>], <span class="at">na.rm =</span> <span class="cn">TRUE</span>)</span></code></pre></div>
<p>Note that we can also access column three by using the <code>$</code> sign and the name of the relevant column (in this case <code>bill_length</code>).
We could therefore get the same answer as above using the code below.</p>
<div class="sourceCode" id="cb166"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb166-1"><a href="practical.-using-r.html#cb166-1" aria-hidden="true" tabindex="-1"></a><span class="fu">mean</span>(<span class="at">x =</span> penguins<span class="sc">$</span>bill_length, <span class="at">na.rm =</span> <span class="cn">TRUE</span>)</span></code></pre></div>
<p>There is usually more than one way of doing the same thing in R (we could also use <code>penguins[["bill_length"]]</code>).</p>
<blockquote>
<p>Task 4: Find the mean bill length of penguins in mm (column 3)</p>
</blockquote>
<p>Mean bill length (mm): _________________________________________________________</p>
<p>Now we can try 2 more functions.
The function <code>sd</code> returns the standard deviation of numbers (note that while <code>na.rm</code> is not an argument for every R function, it can also be used as an argument in <code>sd</code>).
The function <code>length</code> returns the length of an object.
Try using these functions to calculate the 95 per cent confidence intervals for mean bill length (you can use a z-score of 1.96).</p>
<blockquote>
<p>Task 5: Calculate lower and upper confidence intervals (CIs) using the R functions <code>mean</code>, <code>sd</code>, and <code>length</code>.</p>
</blockquote>
<p>Lower bill length CI: __________________________________________________________</p>
<p>Upper bill length CI: __________________________________________________________</p>
<p>Next, we can use the penguins dataset to run a one-way ANOVA, two-way ANOVA, <span class="math inline">\(\chi^{2}\)</span> tests, correlation test, and linear regression.
This practical will walk you through the code so that you can focus on understanding the R output.</p>
</div>
<div id="familiar-statistical-tests-in-r" class="section level2 hasAnchor" number="37.2">
<h2><span class="header-section-number">37.2</span> Familiar statistical tests in R<a href="practical.-using-r.html#familiar-statistical-tests-in-r" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>In this exercise, we will use the penguins dataset to run some familiar statistical hypothesis tests.
In R, there is typically more than one way to do something.
We will focus on the simplest way to run a one-way ANOVA, two-way ANOVA, <span class="math inline">\(\chi^{2}\)</span> tests, correlation test, and linear regression.</p>
<div id="one-way-anova-in-r" class="section level3 hasAnchor" number="37.2.1">
<h3><span class="header-section-number">37.2.1</span> One-way ANOVA in R<a href="practical.-using-r.html#one-way-anova-in-r" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>We can start by running a one-way ANOVA to test the null hypothesis that all species have the same mean bill length.
Normally we would want to first check the assumptions of the ANOVA.
For now, we will assume that no assumptions are violated, but the Shapiro-Wilk test and Levene’s test of equal variances will be demonstrated later.
To run a one-way ANOVA in R, we can use the code below.</p>
<div class="sourceCode" id="cb167"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb167-1"><a href="practical.-using-r.html#cb167-1" aria-hidden="true" tabindex="-1"></a>anova_model <span class="ot">&lt;-</span> <span class="fu">lm</span>(<span class="at">formula =</span> bill_length <span class="sc">~</span> species, <span class="at">data =</span> penguins);</span>
<span id="cb167-2"><a href="practical.-using-r.html#cb167-2" aria-hidden="true" tabindex="-1"></a><span class="fu">anova</span>(anova_model);</span></code></pre></div>
<p>The function <code>lm</code> runs a general linear model (we have not discussed it in this module, but t-tests, ANOVA, and linear regression are all based on <a href="https://stirlingcodingclub.github.io/linear_modelling/">the same mathematical framework</a>; see <a href="#Chapter_38">Chapter 38</a> for more explanation).
We can use the column names <code>bill_length</code> and <code>species</code> directly if we specify that we are using the dataset in which these columns are found (<code>penguins</code>).
Inside <code>lm</code>, you will notice the <code>~</code> symbol. This just separates our dependent variable (<code>bill_length</code> on the left) and independent variable (<code>species</code> on the right).</p>
<p>In the above, we are storing this model with a new variable named <code>anova_model</code> (note that we can use <code>&lt;-</code> to store more than just lists of numbers; in this case, our object is the whole linear model!).
The function <code>anova</code> then summarises this model.</p>
<blockquote>
<p>Task 6: Use the code above to run an ANOVA to test the null hypothesis that species have the same bill length. Find the F value and p value from the output.</p>
</blockquote>
<p>Note that R uses scientific notation to write very low values. For example <code>5.5e-4</code> would be interpreted as <span class="math inline">\(5.5 \times 10^{-4}\)</span>, which is 0.00055.</p>
<p>F value: _______________________________________________________________________</p>
<p>p value: _______________________________________________________________________</p>
</div>
<div id="two-way-anova-in-r" class="section level3 hasAnchor" number="37.2.2">
<h3><span class="header-section-number">37.2.2</span> Two-way ANOVA in R<a href="practical.-using-r.html#two-way-anova-in-r" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>We can run a two-way ANOVA using the independent variables ‘species’ and ‘year’ with the code below.</p>
<div class="sourceCode" id="cb168"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb168-1"><a href="practical.-using-r.html#cb168-1" aria-hidden="true" tabindex="-1"></a>two_way_aov <span class="ot">&lt;-</span> <span class="fu">lm</span>(<span class="at">formula =</span>  bill_length <span class="sc">~</span> species <span class="sc">+</span> year <span class="sc">+</span> species<span class="sc">:</span>year, </span>
<span id="cb168-2"><a href="practical.-using-r.html#cb168-2" aria-hidden="true" tabindex="-1"></a>                  <span class="at">data =</span> penguins);</span>
<span id="cb168-3"><a href="practical.-using-r.html#cb168-3" aria-hidden="true" tabindex="-1"></a><span class="fu">anova</span>(two_way_aov);</span></code></pre></div>
<p>Note that the code above looks very similar to our one way ANOVA.
Now we are just adding a new independent variable with the <code>+</code> sign, and adding an interaction between species and island, which is written as <code>species:year</code>.</p>
<blockquote>
<p>Task 7: Use the code above to run a two way ANOVA. Determine whether or not the the main effects of the model (species and sex) are significant, and whether the interaction terms are significant.</p>
</blockquote>
<p>Significance: Species? __________ Sex? _____________ Interaction? _____________</p>
</div>
<div id="chi-square-test-in-r" class="section level3 hasAnchor" number="37.2.3">
<h3><span class="header-section-number">37.2.3</span> Chi-square test in R<a href="practical.-using-r.html#chi-square-test-in-r" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>To run a <span class="math inline">\(\chi^{2}\)</span> goodness of fit test, we need to first put the data in a table form.
Suppose that we wanted to test the null hypothesis that penguins were sampled from equal frequencies across all islands.
We can use the <code>table</code> function in R to first build a contingency table of counts of penguins observed on each island.</p>
<div class="sourceCode" id="cb169"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb169-1"><a href="practical.-using-r.html#cb169-1" aria-hidden="true" tabindex="-1"></a>island_table <span class="ot">&lt;-</span> <span class="fu">table</span>(penguins<span class="sc">$</span>island);</span>
<span id="cb169-2"><a href="practical.-using-r.html#cb169-2" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(island_table);</span></code></pre></div>
<pre><code>
   Biscoe     Dream Torgersen 
      168       124        52 </code></pre>
<p>The contingency table generated using the <code>table</code> function reveals that there were 168 penguins observed on the island Biscoe, 124 penguins observed on the island Dream, and 52 penguins observed on the island Torgersen.
To run a <span class="math inline">\(\chi^{2}\)</span> goodness of fit test, we can use the <code>island_table</code> that we just created in the function <code>chisq.test</code>.</p>
<div class="sourceCode" id="cb171"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb171-1"><a href="practical.-using-r.html#cb171-1" aria-hidden="true" tabindex="-1"></a><span class="fu">chisq.test</span>(island_table);</span></code></pre></div>
<p>The output of <code>chisq.test</code> will include the <span class="math inline">\(\chi^{2}\)</span> statistic (‘X-squared’), the degrees of freedom (‘df’), and the p-value.</p>
<blockquote>
<p>Task 8: Use the code above to run a Chi-square goodness of fit test. Report the test statistic below.</p>
</blockquote>
<p><span class="math inline">\(\chi^{2}\)</span> test statistic: _____________________</p>
<p>A <span class="math inline">\(\chi^{2}\)</span> test of association also requires counts to be placed in the format of a contingency table.
This can be done by including 2 variables as arguments in <code>table</code>.
We can build a contingency table of penguin counts for each island.</p>
<div class="sourceCode" id="cb172"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb172-1"><a href="practical.-using-r.html#cb172-1" aria-hidden="true" tabindex="-1"></a>sp_island_table <span class="ot">&lt;-</span> <span class="fu">table</span>(penguins<span class="sc">$</span>island, penguins<span class="sc">$</span>species);</span>
<span id="cb172-2"><a href="practical.-using-r.html#cb172-2" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(sp_island_table);</span></code></pre></div>
<pre><code>           
            Adelie Chinstrap Gentoo
  Biscoe        44         0    124
  Dream         56        68      0
  Torgersen     52         0      0</code></pre>
<p>The <code>chisq.test</code> function can then be run directly with this new table <code>sp_island_table</code> as an argument to run a <span class="math inline">\(\chi^{2}\)</span> test of association.</p>
<div class="sourceCode" id="cb174"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb174-1"><a href="practical.-using-r.html#cb174-1" aria-hidden="true" tabindex="-1"></a><span class="fu">chisq.test</span>(sp_island_table);</span></code></pre></div>
<blockquote>
<p>Task 9: Use the code above to run a Chi-square test of association between penguin species and island counts. Report the test statistic below.</p>
</blockquote>
<p><span class="math inline">\(\chi^{2}\)</span> test statistic: _____________________</p>
<p><strong>Correlation</strong>. We can now look at how to find the correlation between two variables in R, and how to test whether or not they are significant. Suppose that we want to test whether or not bill length and flipper length are correlated in penguins.</p>
<p>Remember that we should use the Pearson correlation coefficent if both of our variables are normally distributed, and we should use the Spearman Rank correlation coefficient if either of our variables are not normally distributed. Hence, this is a good time to introduce tests of normality. Given the sample size (n &gt; 30), we would typically recommend a Kolmogorov-Smirnov test of normality in this module. This is possible in R, but requires installing a new package (see the appendix below to do this and run the test). Instead, we can look at a Q-Q plot with the code below. First we can look at a Q-Q plot for bill depth.</p>
<div class="sourceCode" id="cb175"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb175-1"><a href="practical.-using-r.html#cb175-1" aria-hidden="true" tabindex="-1"></a><span class="fu">qqnorm</span>(<span class="at">y =</span> penguins<span class="sc">$</span>bill_depth) <span class="co"># This makes a plot for bill depth</span></span>
<span id="cb175-2"><a href="practical.-using-r.html#cb175-2" aria-hidden="true" tabindex="-1"></a><span class="fu">qqline</span>(<span class="at">y =</span> penguins<span class="sc">$</span>bill_depth) <span class="co"># This adds a line for bill depth</span></span></code></pre></div>
<p>Next, we can look at a Q-Q plot for flipper length.</p>
<div class="sourceCode" id="cb176"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb176-1"><a href="practical.-using-r.html#cb176-1" aria-hidden="true" tabindex="-1"></a><span class="fu">qqnorm</span>(<span class="at">y =</span> penguins<span class="sc">$</span>flipper_length) <span class="co"># This makes a plot for flipper length</span></span>
<span id="cb176-2"><a href="practical.-using-r.html#cb176-2" aria-hidden="true" tabindex="-1"></a><span class="fu">qqline</span>(<span class="at">y =</span> penguins<span class="sc">$</span>flipper_length) <span class="co"># This adds a line for flipper length</span></span></code></pre></div>
<blockquote>
<p>Task 3: Use the code above to make a Q-Q plot and decide whether or not the data for bill depth and flipper length are normally distributed.</p>
</blockquote>
<p>Neither of these Q-Q plots look very encouraging. In both cases, the extreme values do not fit on the line very well, which suggests that our data do not match the theoretical expectations of the normal distribution. If we run a Shapiro-Wilk test of normality for each variable, we get a very low p-value, which is yet more evidence that we should reject the null hypothesis that our data are normally distributed.</p>
<div class="sourceCode" id="cb177"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb177-1"><a href="practical.-using-r.html#cb177-1" aria-hidden="true" tabindex="-1"></a><span class="fu">shapiro.test</span>(<span class="at">x =</span> penguins<span class="sc">$</span>bill_depth) <span class="co"># Shapiro test for bill depth</span></span>
<span id="cb177-2"><a href="practical.-using-r.html#cb177-2" aria-hidden="true" tabindex="-1"></a><span class="fu">shapiro.test</span>(<span class="at">x =</span> penguins<span class="sc">$</span>flipper_length) <span class="co"># Shapiro test for flipper length</span></span></code></pre></div>
<p>If we were to use the Kolmogorov-Smirnov test of normality (see the appendix below), this would also reject our null hypothesis that the data are normally distributed. We should therefore use a Spearman’s Rank correlation coefficient to test our null hypothesis that the correlation coefficient between bill depth and flipper length is zero. But first, we should use a scatterplot to visualise the data.</p>
<div class="sourceCode" id="cb178"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb178-1"><a href="practical.-using-r.html#cb178-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(<span class="at">x =</span> penguins<span class="sc">$</span>bill_depth, <span class="at">y =</span> penguins<span class="sc">$</span>flipper_length,</span>
<span id="cb178-2"><a href="practical.-using-r.html#cb178-2" aria-hidden="true" tabindex="-1"></a>     <span class="at">xlab =</span> <span class="st">&quot;Bill depth (mm)&quot;</span>, <span class="at">ylab =</span> <span class="st">&quot;Flipper length (mm)&quot;</span>)</span></code></pre></div>
<p>The arguments <code>xlab</code> and <code>ylab</code> above tell R what to label the x and y axes (if we leave them out, then R will just default to the variable names).</p>
<blockquote>
<p>Task 4: Make a scatterplot showing penguin bill depth versus flipper length in R. Is there anything notable about the scatterplot that might be cause for concern? If so, explain what you think might be happening.</p>
</blockquote>
<pre><code>








</code></pre>
<p>Now we can run our test of the correlation coefficient using the R function <code>cor.test</code> in the code below.</p>
<div class="sourceCode" id="cb180"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb180-1"><a href="practical.-using-r.html#cb180-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cor.test</span>(<span class="at">x =</span> penguins<span class="sc">$</span>bill_depth, <span class="at">y =</span> penguins<span class="sc">$</span>flipper_length, </span>
<span id="cb180-2"><a href="practical.-using-r.html#cb180-2" aria-hidden="true" tabindex="-1"></a>         <span class="at">method =</span> <span class="st">&quot;spearman&quot;</span>)</span></code></pre></div>
<p>Note in the above that we are specifying the method as <code>method = "spearman"</code>, which will tell R to use the Spearman Rank correlation coefficient instead of the default <code>method = "pearson"</code>. The R output might give a warning that it cannot compute an exact p-value with ties, but this is really only a concern if our p-value is marginal (i.e., near our threshold of 0.05).</p>
<blockquote>
<p>Task 5: Test whether or not bill depth and flipper length are correlated using a Spearman’s Rank correlation coefficient. Report the test statistic (called ‘rho’ in the output). Based just on this hypothesis test, what would you conclude?</p>
</blockquote>
<p>Test statistic: ________________________________________________________________</p>
<p>Conclusion: ____________________________________________________________________</p>
<blockquote>
<p>Task 6: Based on your earlier plot from Task 4, do you trust the interpretation that bill depth and flipper length are negatively correlated? Why or why not?</p>
</blockquote>
<pre><code>








</code></pre>
<p><strong>Simple linear regression</strong>. Suppose we want to try to predict penguin body mass from bill length. How would we run a simple linear regression for this in R? The code is actually very similar to what we used for running an ANOVA (again, they actually are based on <a href="https://stirlingcodingclub.github.io/linear_modelling/">the same mathematical framework</a>); we can again use the function <code>lm</code>. For simplicity, and because the goal here is just to show how to use the R functions, we will just assume that all of the relevant assumptions of regression are true. In this case, our linear model can be run using the code below.</p>
<div class="sourceCode" id="cb182"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb182-1"><a href="practical.-using-r.html#cb182-1" aria-hidden="true" tabindex="-1"></a>lin_mod <span class="ot">&lt;-</span> <span class="fu">lm</span>(<span class="at">formula =</span> mass <span class="sc">~</span> bill_length, <span class="at">data =</span> penguins)</span>
<span id="cb182-2"><a href="practical.-using-r.html#cb182-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(lin_mod)</span></code></pre></div>
<p>In the above code, the first line defines the model (<code>lin_mod</code>), and the second line summarises it for us with the output we need to make conclusions. Notice that the first line has the exact same structure as we used in the ANOVA. In the formula, the dependent variable <code>mass</code> is separated from the independent variable <code>bill_length</code> with the <code>~</code> character, and we specify the dataset for both variables (<code>penguins</code>).</p>
<blockquote>
<p>Task 7: Examine the output of the simple regression of penguin body mass against bill depth from the code above. Find the R-squared value (called ‘Multiple R-squared’), intercept, slope, and p-value for the overall model.</p>
</blockquote>
<p>R-squared: _____________________________________________________________________</p>
<p>Intercept: _____________________________________________________________________</p>
<p>Slope: _________________________________________________________________________</p>
<p>Model p-value: _________________________________________________________________</p>
<p>Note that the p-value for the model is in the very bottom right of the output.</p>
<p><strong>Multiple regression</strong>. Now we can add to the complexity of our model by including another independent variable. Suppose we want to predict body mass from both bill length and flipper length. Again, assume that all of the assumptions of regression are met; the goal is just to show the R functions at work. For multiple regression, the code again looks suspiciously similar to what it does for a two-way ANOVA (note, we should really also consider an interaction between our independent variables in multiple regression too, but for now we will just assume that none exists).</p>
<div class="sourceCode" id="cb183"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb183-1"><a href="practical.-using-r.html#cb183-1" aria-hidden="true" tabindex="-1"></a>mult_regr <span class="ot">&lt;-</span> <span class="fu">lm</span>(<span class="at">formula =</span> mass <span class="sc">~</span> bill_length <span class="sc">+</span> bill_depth, </span>
<span id="cb183-2"><a href="practical.-using-r.html#cb183-2" aria-hidden="true" tabindex="-1"></a>                <span class="at">data =</span> penguins)</span>
<span id="cb183-3"><a href="practical.-using-r.html#cb183-3" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(mult_regr)</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = mass ~ bill_length + bill_depth, data = penguins)
## 
## Residuals:
##      Min       1Q   Median       3Q      Max 
## -1804.61  -454.83     8.15   463.53  1544.82 
## 
## Coefficients:
##             Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept) 3343.136    429.912   7.776 9.05e-14 ***
## bill_length   75.281      5.971  12.608  &lt; 2e-16 ***
## bill_depth  -142.723     16.507  -8.646  &lt; 2e-16 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 585.1 on 339 degrees of freedom
##   (2 observations deleted due to missingness)
## Multiple R-squared:  0.4708, Adjusted R-squared:  0.4677 
## F-statistic: 150.8 on 2 and 339 DF,  p-value: &lt; 2.2e-16</code></pre>
<p>The output above looks similar to that of our simple linear model, but we now have a coefficient and p-value for an additional independent variable (bill depth).</p>
<blockquote>
<p>Task 8: Examine the output of the multiple regression from the code above. Find the adjusted R-squared value, and write down the equation of the model.</p>
</blockquote>
<p>Adjusted R-squared: ____________________________________________________________</p>
<p>Model equation: ________________________________________________________________</p>
<blockquote>
<p>Task 9: Notice that the regression coefficient for bill length has changed in the multiple regression model from what it was in the simple linear regression. Why would this be?</p>
</blockquote>
<pre><code>





</code></pre>
<p>For some help, it might be good to review Lecture 12 on multiple regression (see the first video ‘introduction_to_multiple_regression’ at around the 2:43 minute mark).</p>
</div>
</div>
<div id="reading-and-writing-data-in-r" class="section level2 hasAnchor" number="37.3">
<h2><span class="header-section-number">37.3</span> Reading and writing data in R<a href="practical.-using-r.html#reading-and-writing-data-in-r" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>This last exercise is focused on reading data into R and writing it to an external file. Like everything in R, there are many ways to do this, so we will focus on the simple case of reading in and out a simple Comma-Separated Values (CSV) file. A CSV file is a plain text file that, as the name implies, uses commas to separate values. To upload a file to the Rstudio Cloud, find the ‘Files’ tab in the lower right and click the button underneath named ‘Upload’. A box should pop up so that you can select a file to upload from your computer.</p>
<p><img src="img/upload.png" /></p>
<p>We can now upload a file to the Rstudio Cloud</p>
<blockquote>
<p>Task 1: Download the file ‘Bumpus_data.csv’ from Canvas to your computer, then upload the file to the Rstudio Cloud.</p>
</blockquote>
<p>We now need to read the file into R so that we can work with it in the R console. In either the R console or your R script, we can use the code below to read the CSV file into R.</p>
<div class="sourceCode" id="cb186"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb186-1"><a href="practical.-using-r.html#cb186-1" aria-hidden="true" tabindex="-1"></a>bumpus <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="at">file =</span> <span class="st">&quot;Bumpus_data.csv&quot;</span>, <span class="at">header =</span> <span class="cn">TRUE</span>)</span></code></pre></div>
<p>The quotations around “Bumpus_data.csv” are important; if we do not include them, then R will try to look for an object of the same name (which probably does not exist; remove the quotations and re-run the code to see the error message).</p>
<blockquote>
<p>Task 2: Read the Bumpus_data.csv data file into Rstudio.</p>
</blockquote>
<p>We can get a sense of what the data look like using the <code>head</code> function in R, which will show us the first six rows of the dataset.</p>
<div class="sourceCode" id="cb187"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb187-1"><a href="practical.-using-r.html#cb187-1" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(bumpus)</span></code></pre></div>
<p>Suppose that the total length (<code>totlen</code>) of the sparrow in the second row was written down incorrectly. We can use R to change the value (for a reminder, see Task 2 in Exercise 1).</p>
<blockquote>
<p>Task 3: Change the <code>totlen</code> of the sparrow in row 2 from 160 to 155.</p>
</blockquote>
<p>Now, we can save the data set in R using the <code>write.csv</code> function using the code below.</p>
<div class="sourceCode" id="cb188"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb188-1"><a href="practical.-using-r.html#cb188-1" aria-hidden="true" tabindex="-1"></a><span class="fu">write.csv</span>(<span class="at">x =</span> bumpus, <span class="at">file =</span> <span class="st">&quot;Bumpus_data_new.csv&quot;</span>, <span class="at">row.names =</span> <span class="cn">FALSE</span>)</span></code></pre></div>
<p>By default <code>row.names = TRUE</code>, which would add a column of row numbers to our data file that we really do not want.</p>
<blockquote>
<p>Task 4: Write a new CSV file with the corrected total length of sparrow number two.</p>
</blockquote>
<p>A new file will now appear in the ‘Files’ tab of Rstudio. We can download this file and open it in Excel (or any text editor), and use it in SPSS by selecting ‘File &gt; Import Data &gt; CSV Data…’.</p>
</div>
<div id="appendix" class="section level2 hasAnchor" number="37.4">
<h2><span class="header-section-number">37.4</span> Appendix<a href="practical.-using-r.html#appendix" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p><strong>Levene’s test of equal variances.</strong> To run a Levene’s test, we need to first install and load the ‘car’ package in R.</p>
<div class="sourceCode" id="cb189"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb189-1"><a href="practical.-using-r.html#cb189-1" aria-hidden="true" tabindex="-1"></a><span class="fu">install.packages</span>(<span class="st">&quot;car&quot;</span>)</span>
<span id="cb189-2"><a href="practical.-using-r.html#cb189-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(<span class="st">&quot;car&quot;</span>)</span></code></pre></div>
<p>With the ‘car’ package installed, we can run a Levene’s test to test for homogeneity of variances among species using the function <code>leveneTest</code> as below.</p>
<div class="sourceCode" id="cb190"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb190-1"><a href="practical.-using-r.html#cb190-1" aria-hidden="true" tabindex="-1"></a><span class="fu">leveneTest</span>(bill_length <span class="sc">~</span> species, <span class="at">data =</span> penguins)</span></code></pre></div>
<p><strong>Kolmogorov-Smirnov test of normality</strong>. To run a Kolmogorov-Smirnov test of normality, we need to first install and load the ‘nortest’ package in R.</p>
<div class="sourceCode" id="cb191"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb191-1"><a href="practical.-using-r.html#cb191-1" aria-hidden="true" tabindex="-1"></a><span class="fu">install.packages</span>(<span class="st">&quot;nortest&quot;</span>)</span>
<span id="cb191-2"><a href="practical.-using-r.html#cb191-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(<span class="st">&quot;nortest&quot;</span>)</span></code></pre></div>
<p>With the ‘nortest’ package installed, we can run a Kolmogorov-Smirnov test of normality using the function <code>lillie.test</code> as below (recall that column 3 of the <code>penguins</code> dataset is <code>bill_length</code>).</p>
<div class="sourceCode" id="cb192"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb192-1"><a href="practical.-using-r.html#cb192-1" aria-hidden="true" tabindex="-1"></a><span class="fu">lillie.test</span>(penguins<span class="sc">$</span>bill_length); </span></code></pre></div>
<p><strong>Code used in the practical</strong>. A summary of the code used in the practical is below.</p>
<div class="sourceCode" id="cb193"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb193-1"><a href="practical.-using-r.html#cb193-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Exercise 1</span></span>
<span id="cb193-2"><a href="practical.-using-r.html#cb193-2" aria-hidden="true" tabindex="-1"></a><span class="fu">install.packages</span>(<span class="st">&quot;palmerpenguins&quot;</span>)</span>
<span id="cb193-3"><a href="practical.-using-r.html#cb193-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(<span class="st">&quot;palmerpenguins&quot;</span>)</span>
<span id="cb193-4"><a href="practical.-using-r.html#cb193-4" aria-hidden="true" tabindex="-1"></a>penguins</span>
<span id="cb193-5"><a href="practical.-using-r.html#cb193-5" aria-hidden="true" tabindex="-1"></a>penguins[, <span class="dv">3</span>]</span>
<span id="cb193-6"><a href="practical.-using-r.html#cb193-6" aria-hidden="true" tabindex="-1"></a><span class="fu">mean</span>(<span class="at">x =</span> penguins[,<span class="dv">3</span>])</span>
<span id="cb193-7"><a href="practical.-using-r.html#cb193-7" aria-hidden="true" tabindex="-1"></a><span class="fu">mean</span>(<span class="at">x =</span> penguins[,<span class="dv">3</span>], <span class="at">na.rm =</span> <span class="cn">TRUE</span>)</span>
<span id="cb193-8"><a href="practical.-using-r.html#cb193-8" aria-hidden="true" tabindex="-1"></a><span class="fu">mean</span>(<span class="at">x =</span> penguins<span class="sc">$</span>bill_length, <span class="at">na.rm =</span> <span class="cn">TRUE</span>)</span>
<span id="cb193-9"><a href="practical.-using-r.html#cb193-9" aria-hidden="true" tabindex="-1"></a>mean_bill_length <span class="ot">&lt;-</span> <span class="fu">mean</span>(penguins<span class="sc">$</span>bill_length, <span class="at">na.rm =</span> <span class="cn">TRUE</span>)</span>
<span id="cb193-10"><a href="practical.-using-r.html#cb193-10" aria-hidden="true" tabindex="-1"></a>sd_bill_length   <span class="ot">&lt;-</span> <span class="fu">sd</span>(penguins<span class="sc">$</span>bill_length, <span class="at">na.rm =</span> <span class="cn">TRUE</span>)</span>
<span id="cb193-11"><a href="practical.-using-r.html#cb193-11" aria-hidden="true" tabindex="-1"></a>N_bill_length    <span class="ot">&lt;-</span> <span class="fu">length</span>(penguins<span class="sc">$</span>bill_length)</span>
<span id="cb193-12"><a href="practical.-using-r.html#cb193-12" aria-hidden="true" tabindex="-1"></a>mean_bill_length <span class="sc">-</span> <span class="fl">1.96</span> <span class="sc">*</span> (sd_bill_length <span class="sc">/</span> <span class="fu">sqrt</span>(N_bill_length))</span>
<span id="cb193-13"><a href="practical.-using-r.html#cb193-13" aria-hidden="true" tabindex="-1"></a>mean_bill_length <span class="sc">+</span> <span class="fl">1.96</span> <span class="sc">*</span> (sd_bill_length <span class="sc">/</span> <span class="fu">sqrt</span>(N_bill_length))</span>
<span id="cb193-14"><a href="practical.-using-r.html#cb193-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb193-15"><a href="practical.-using-r.html#cb193-15" aria-hidden="true" tabindex="-1"></a><span class="co"># Exercise 2</span></span>
<span id="cb193-16"><a href="practical.-using-r.html#cb193-16" aria-hidden="true" tabindex="-1"></a>anova_model <span class="ot">&lt;-</span> <span class="fu">lm</span>(<span class="at">formula =</span> bill_length <span class="sc">~</span> species, <span class="at">data =</span> penguins)</span>
<span id="cb193-17"><a href="practical.-using-r.html#cb193-17" aria-hidden="true" tabindex="-1"></a><span class="fu">anova</span>(anova_model)</span>
<span id="cb193-18"><a href="practical.-using-r.html#cb193-18" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb193-19"><a href="practical.-using-r.html#cb193-19" aria-hidden="true" tabindex="-1"></a>two_way_aov <span class="ot">&lt;-</span> <span class="fu">lm</span>(<span class="at">formula =</span>  bill_length <span class="sc">~</span> species <span class="sc">+</span> sex <span class="sc">+</span> species<span class="sc">:</span>sex, </span>
<span id="cb193-20"><a href="practical.-using-r.html#cb193-20" aria-hidden="true" tabindex="-1"></a>                  <span class="at">data =</span> penguins)</span>
<span id="cb193-21"><a href="practical.-using-r.html#cb193-21" aria-hidden="true" tabindex="-1"></a><span class="fu">anova</span>(two_way_aov)</span>
<span id="cb193-22"><a href="practical.-using-r.html#cb193-22" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb193-23"><a href="practical.-using-r.html#cb193-23" aria-hidden="true" tabindex="-1"></a><span class="fu">qqnorm</span>(<span class="at">y =</span> penguins<span class="sc">$</span>bill_depth) <span class="co"># This makes a plot for bill depth</span></span>
<span id="cb193-24"><a href="practical.-using-r.html#cb193-24" aria-hidden="true" tabindex="-1"></a><span class="fu">qqline</span>(<span class="at">y =</span> penguins<span class="sc">$</span>bill_depth) <span class="co"># This adds a line for bill depth</span></span>
<span id="cb193-25"><a href="practical.-using-r.html#cb193-25" aria-hidden="true" tabindex="-1"></a><span class="fu">qqnorm</span>(<span class="at">y =</span> penguins<span class="sc">$</span>flipper_length) <span class="co"># This makes a plot for flipper length</span></span>
<span id="cb193-26"><a href="practical.-using-r.html#cb193-26" aria-hidden="true" tabindex="-1"></a><span class="fu">qqline</span>(<span class="at">y =</span> penguins<span class="sc">$</span>flipper_length) <span class="co"># This adds a line for flipper length</span></span>
<span id="cb193-27"><a href="practical.-using-r.html#cb193-27" aria-hidden="true" tabindex="-1"></a><span class="fu">shapiro.test</span>(<span class="at">x =</span> penguins<span class="sc">$</span>bill_depth) <span class="co"># Shapiro test for bill depth</span></span>
<span id="cb193-28"><a href="practical.-using-r.html#cb193-28" aria-hidden="true" tabindex="-1"></a><span class="fu">shapiro.test</span>(<span class="at">x =</span> penguins<span class="sc">$</span>flipper_length) <span class="co"># Shapiro test for flipper length</span></span>
<span id="cb193-29"><a href="practical.-using-r.html#cb193-29" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(<span class="at">x =</span> penguins<span class="sc">$</span>bill_depth, <span class="at">y =</span> penguins<span class="sc">$</span>flipper_length,</span>
<span id="cb193-30"><a href="practical.-using-r.html#cb193-30" aria-hidden="true" tabindex="-1"></a>     <span class="at">xlab =</span> <span class="st">&quot;Bill depth (mm)&quot;</span>, <span class="at">ylab =</span> <span class="st">&quot;Flipper length (mm)&quot;</span>)</span>
<span id="cb193-31"><a href="practical.-using-r.html#cb193-31" aria-hidden="true" tabindex="-1"></a><span class="fu">cor.test</span>(<span class="at">x =</span> penguins<span class="sc">$</span>bill_depth, <span class="at">y =</span> penguins<span class="sc">$</span>flipper_length, </span>
<span id="cb193-32"><a href="practical.-using-r.html#cb193-32" aria-hidden="true" tabindex="-1"></a>         <span class="at">method =</span> <span class="st">&quot;spearman&quot;</span>)</span>
<span id="cb193-33"><a href="practical.-using-r.html#cb193-33" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb193-34"><a href="practical.-using-r.html#cb193-34" aria-hidden="true" tabindex="-1"></a>lin_mod <span class="ot">&lt;-</span> <span class="fu">lm</span>(<span class="at">formula =</span> mass <span class="sc">~</span> bill_length, <span class="at">data =</span> penguins)</span>
<span id="cb193-35"><a href="practical.-using-r.html#cb193-35" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(lin_mod)</span>
<span id="cb193-36"><a href="practical.-using-r.html#cb193-36" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb193-37"><a href="practical.-using-r.html#cb193-37" aria-hidden="true" tabindex="-1"></a>mult_regr <span class="ot">&lt;-</span> <span class="fu">lm</span>(<span class="at">formula =</span> mass <span class="sc">~</span> bill_length <span class="sc">+</span> bill_depth, </span>
<span id="cb193-38"><a href="practical.-using-r.html#cb193-38" aria-hidden="true" tabindex="-1"></a>                <span class="at">data =</span> penguins)</span>
<span id="cb193-39"><a href="practical.-using-r.html#cb193-39" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(mult_regr)</span>
<span id="cb193-40"><a href="practical.-using-r.html#cb193-40" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb193-41"><a href="practical.-using-r.html#cb193-41" aria-hidden="true" tabindex="-1"></a><span class="co"># Exercise 3</span></span>
<span id="cb193-42"><a href="practical.-using-r.html#cb193-42" aria-hidden="true" tabindex="-1"></a>bumpus <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="at">file =</span> <span class="st">&quot;Bumpus_data.csv&quot;</span>, <span class="at">header =</span> <span class="cn">TRUE</span>)</span>
<span id="cb193-43"><a href="practical.-using-r.html#cb193-43" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(bumpus)</span>
<span id="cb193-44"><a href="practical.-using-r.html#cb193-44" aria-hidden="true" tabindex="-1"></a>bumpus[<span class="dv">2</span>, <span class="dv">3</span>] <span class="sc">&lt;</span> <span class="dv">155</span></span>
<span id="cb193-45"><a href="practical.-using-r.html#cb193-45" aria-hidden="true" tabindex="-1"></a><span class="fu">write.csv</span>(<span class="at">x =</span> bumpus, <span class="at">file =</span> <span class="st">&quot;Bumpus_data_new.csv&quot;</span>, <span class="at">row.names =</span> <span class="cn">FALSE</span>)</span></code></pre></div>

</div>
</div>



<h3>References<a href="references.html#references" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<div id="refs" class="references csl-bib-body hanging-indent">
<div id="ref-GormanEtAl2014" class="csl-entry">
Gorman, Kristen B, Tony D Williams, and William R Fraser. 2014. <span>“Ecological Sexual Dimorphism and Environmental Variability Within a Community of Antarctic Penguins (Genus Pygoscelis).”</span> <em>PloS One</em> 9 (3): e90081.
</div>
<div id="ref-HorstEtAl2020" class="csl-entry">
Horst, Allison Marie, Alison Presmanes Hill, and Kristen B Gorman. 2020. <em>Palmerpenguins: Palmer Archipelago (Antarctica) Penguin Data</em>. <a href="https://doi.org/10.5281/zenodo.3960218">https://doi.org/10.5281/zenodo.3960218</a>.
</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="reporting-statistics.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="Week13.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"whatsapp": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": "https://github.com/rstudio/bookdown-demo/edit/master/12-Statistical_Reporting.Rmd",
"text": "Edit"
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": ["bookdown-demo.pdf", "bookdown-demo.epub"],
"search": {
"engine": "fuse",
"options": null
},
"toc": {
"collapse": "subsection"
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
